service: The-Team-SP23
frameworkVersion: '3'

provider:
  httpApi:
    cors: true
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    PERSONAL_TABLE:
      Ref: PersonalDevTable
  iamRoleStatements:
    - Effect: Allow
      Action:
            - dynamodb:*
      Resource:
        - "Fn::GetAtt": [PersonalDevTable, Arn]

functions:
  createPDT:
    handler: createPDT.createPDT
    events:
      - httpApi:
          path: /PDT
          method: POST
  listItems:
    handler: listItems.listItems
    events:
      - httpApi:
          path: /{model}
          method: GET
  getItem:
    handler: getItem.getItem
    events:
      - httpApi:
          path: /{model}/{id}
          method: GET

resources:
  Resources:
    PersonalDevTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonalDevTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1