service: The-Team-SP23
frameworkVersion: '3'

provider:
  httpApi:
    cors: true
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  environment:
    PERSONAL_TABLE:
      Ref: PersonalDevTable
    SELF_TABLE:
      Ref: SelfAssementTable
    PREFORMANCE_TABLE:
      Ref: PreformanceEvaluationTable
  iamRoleStatements:
    - Effect: Allow
      Action:
            - dynamodb:*
      Resource:
        - "Fn::GetAtt": [PersonalDevTable, Arn]
        - "Fn::GetAtt": [SelfAssementTable, Arn]
        - "Fn::GetAtt": [PreformanceEvaluationTable, Arn]

functions:
  createPDT:
    handler: createPDT.createPDT
    events:
      - httpApi:
          path: /PDT
          method: POST
  createPET:
    handler: createPET.createPET
    events:
      - httpApi:
          path: /PET
          method: POST
  createSAT:
    handler: createSAT.createSAT
    events:
      - httpApi:
          path: /SAT
          method: POST
  listItems:
    handler: listItems.listItems
    events:
      - httpApi:
          path: /{model}
          method: GET
  getItem:
    handler: getItem.getItem
    events:
      - httpApi:
          path: /{model}/id/{id}
          method: GET
  getByYear:
    handler: getByYear.getByYear
    events:
      - httpApi:
          path: /{model}/year/{year}
          method: GET
  deleteItem:
    handler: deleteItem.delItem
    events:
      - httpApi:
          path: /{model}/id/{id}
          method: DELETE
  updateTableEntry:
    handler: updateTable.updateTable
    events:
      - httpApi:
          path: /{model}/update/{id}
          method: PUT

resources:
  Resources:
    PersonalDevTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PersonalDevTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    SelfAssementTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SelfAssementTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    PreformanceEvaluationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PreformanceEvaluationTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
  - serverless-dynamodb-local
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: false

custom:
  dynamodb:
    stages:
      - ${opt:stage, 'dev'}
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
